#!/usr/bin/env python3

from __future__ import absolute_import, division, print_function

import time

import opmodaq.modes
import opmodaq.parameters as params
import opmodaq.generators as gen

from opmodaq.devices.mcc import MCCUL


def main():
    osc_sine = gen.Sine(freq   = 4.5,
                        signal = params.Signal(
                                    signal_range = { 0.0, 5.0 },
                                    offset       = 0.0))

    print("Discovering devices ...")
    devices = MCCUL.discover()

    if not devices:
        print("No device found")
        return -1

    dev = devices[0]
    print("Device found, board number:", dev.board_num)

    dev.channel(0).analog_out(osc_sine)


if __name__ == "__main__":
    # execute only if run as a script
    main()

