#!/usr/bin/env python3

from __future__ import absolute_import, division, print_function

import time

import opmodaq.modes
import opmodaq.parameters as params
import opmodaq.generators as gen

from opmodaq.devices.mcc_daq import MCCDAQ


def main():
    osc_sine = gen.Sine(freq   = 4.5,
                        signal = params.Signal(
                                    signal_range = { 0.0, 5.0 },
                                    offset       = 0.0))
    osc_saw  = gen.Saw(freq   = 2.5,
                       signal = params.Signal(
                                    signal_range = { 0.0, 4.5 },
                                    offset       = 0.5))

    print("Discovering devices ...")
    devices = MCCDAQ.discover()

    if not devices:
        print("No DAQ found")
        return -1

    daq = devices[0]
    print("DAQ found, board number:", daq.board_num)

    daq.sampling.frequency = 5000
    
    daq.channel(0).analog_out(osc_sine)


if __name__ == "__main__":
    # execute only if run as a script
    main()

